package be.mgx.util

enum class GraphTypes {
    BASICANDPERCEPTRON,
    LINEARSEPARATION,
    NONLINEARSEPARATION,
    LINEARREGRESSION,
    THREECLASSCLASSIFICATION,
    FOURCLASSCLASSIFICATION,
    XOROPERATOR,
    TWOCLASSNONLINEAR,
    THREECLASSNONLINEAR,
    NONLINEARREGRESSION
}