package be.mgx.util

enum class GraphTypes {
    BASICANDPERCEPTRON,
    ANDPERCEPTRONGRAD,
    ANDPERCEPTRONADALINE,
    LINEARSEPARATIONGRAD,
    LINEARSEPARATIONADALINE,
    NONLINEARSEPARATIONGRAD,
    NONLINEARSEPARATIONADALINE,
    LINEARREGRESSIONGRAD,
    LINEARREGRESSIONADALINE,
    THREECLASSCLASSIFICATION,
    XOROPERATOR,
    TWOCLASSNONLINEAR,
    THREECLASSNONLINEAR,
    NONLINEARREGRESSION
}