package be.mgx.util

enum class GraphTypes {
    BASICANDPERCEPTRON,
    ANDPERCEPTRONGRAD,
    ANDPERCEPTRONADALINE,
    LINEARSEPARATIONGRAD,
    LINEARSEPARATIONADALINE,
    NONLINEARSEPARATION,
    LINEARREGRESSION,
    THREECLASSCLASSIFICATION,
    FOURCLASSCLASSIFICATION,
    XOROPERATOR,
    TWOCLASSNONLINEAR,
    THREECLASSNONLINEAR,
    NONLINEARREGRESSION
}